// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuw8FKApCT6jPiJgt_5CtIwPTjZRBQ_bQ',
    appId: '1:980211073392:web:432fcd5066f8bc2c698fb5',
    messagingSenderId: '980211073392',
    projectId: 'chatting-b4221',
    authDomain: 'chatting-b4221.firebaseapp.com',
    storageBucket: 'chatting-b4221.firebasestorage.app',
    measurementId: 'G-H8ZV9PHWXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbc9Y7-LzQh56kGyeKvyFN7zILdySN2l0',
    appId: '1:980211073392:android:1dc2cfb9b0068a63698fb5',
    messagingSenderId: '980211073392',
    projectId: 'chatting-b4221',
    storageBucket: 'chatting-b4221.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMuYplKrUgM0q8bKcGj734iDgF3Z9KwWo',
    appId: '1:980211073392:ios:afce1fbdf5ea9e22698fb5',
    messagingSenderId: '980211073392',
    projectId: 'chatting-b4221',
    storageBucket: 'chatting-b4221.firebasestorage.app',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMuYplKrUgM0q8bKcGj734iDgF3Z9KwWo',
    appId: '1:980211073392:ios:afce1fbdf5ea9e22698fb5',
    messagingSenderId: '980211073392',
    projectId: 'chatting-b4221',
    storageBucket: 'chatting-b4221.firebasestorage.app',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuw8FKApCT6jPiJgt_5CtIwPTjZRBQ_bQ',
    appId: '1:980211073392:web:a59b0e9fbf694d75698fb5',
    messagingSenderId: '980211073392',
    projectId: 'chatting-b4221',
    authDomain: 'chatting-b4221.firebaseapp.com',
    storageBucket: 'chatting-b4221.firebasestorage.app',
    measurementId: 'G-KQJSGHYQNH',
  );
}
